### ISSUE TITLE
Error when importing CoolInlineEditFieldModule in a lazy loaded module

### ISSUE THREAD

**Issue by solid-flow** [Hacklone/angular-cool#1]
Hi, 
I am trying to use inline edit field in a lazy loaded module and there is an error:
`ERROR Error: Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.`

Could you please update the imports from BrowserModule to CommonModule? 
Thank you

**Comment by Hacklone** [comment]
Thanks for noticing. v1.0.2 should fix this :)
