### ISSUE TITLE
not so cool facebook button

### ISSUE THREAD

**Issue by sixbras** [Hacklone/angular-cool#10]
Hi,
At this time the right tag for facebook button is :
`  <cool-cool-facebook-button color="dark" (click)="">
          Login with Google
        </cool-cool-facebook-button>`
  
Need a double cool.
In cool-facebook-button.component.ts , selector is mispelled.

`@Component({
  selector: 'cool-cool-facebook-button',....
})`

**Comment by yarn-worlds** [comment]
Thanks for the fixing :)
I've fixed it with `v11.1.3`

**Comment by Hacklone** [comment]
Thanks for the finding. :) 
I've fixed it with `v11.1.3`
