### ISSUE TITLE
cool facebook button, not so cool

### ISSUE THREAD

**Issue by sixbras** [Hacklone/angular-cool#11]
Something wrong in the import. "CoolSocialLoginButtonsModule" is the right syntax
![image](https://user-images.githubusercontent.com/4798404/104526824-9d5de880-5603-11eb-93da-57273175eaec.png)

**Comment by sixbras** [comment]
Sorry for the same title ;-)

**Comment by Hacklone** [comment]
No problem, thanks for pointing it out :) Fixed it on master
