### ISSUE TITLE
Github button shows icon way bigger that expected

### ISSUE THREAD

**Issue by mmonteiroc** [Hacklone/angular-cool#45]
<img width="242" alt="Screenshot 2024-07-27 at 17 45 09" src="https://github.com/user-attachments/assets/07dc7951-1deb-4266-92ec-ff6d5976cb4b">

Code to make it happen 

```
<cool-github-button color="dark" (click)="useGithub()">
  Sign in with GitHub
</cool-github-button>
```

**Comment by Hacklone** [comment]
Hey, thanks for reporting. `v18.0.4` fixes this issue.
