### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by ddangxx** [Hacklone/angular-cool#8]
Hi,
Is there a way for us to do validation for the input when using cool inline edit? Like maxLenth, pattern?

Thanks

**Comment by Hacklone** [comment]
Honestly never tried, but by using ReactiveForms you should be able to do it easily.
```typescript
new FormControl('name', [
      Validators.required,
      Validators.minLength(4),
    ])
```

For template driven Forms we could add those properties for the inline-edit component. :)

**Comment by Hacklone** [comment]
Closing due to no interaction
